### ISSUE TITLE
Model supports only targets with even dimensions, need support for uneven dimensions

### ISSUE THREAD

**Issue by JohannesEsslinger** [lollcat/fab-jax#33]
Hi Laurence Midgley,

Thank you for providing the JAX implementation of the FAB model!

I am currently trying to apply your model to targets with uneven dimensions. However, I've encountered an issue as the current implementation does not seem to support this for both the real_nvp and spline flows. As far as I know is that these flows generally support uneven dimensions.

Could you please provide guidance on how to apply FAB to problems with uneven dimensions, if possible?

Kind regards,
Johannes

**Comment by lollcat** [comment]
Hi Johannes,

Thanks for pointing out this issue. I'll fix this over the next few days when I get a chance - should be a minor change to get it to work. 

Cheers,
Laurence

**Comment by lollcat** [comment]
@JohannesEsslinger there was a bug in the coupling split that is now fixed - so the code works for an odd number of dims! Thanks for making the issue!

**Comment by lollcat** [comment]
@JohannesEsslinger feel free to ping me if you need any other help getting the code working nicely for your problem.

**Comment by JohannesEsslinger** [comment]
Thank you for fixing it that quickly!
