### ISSUE TITLE
ScalarAffine Flow Support

### ISSUE THREAD

**Issue by JohannesEsslinger** [lollcat/fab-jax#35]
Hi Laurence,

I would like to test how FAB performs when using a simple Scalar Affine Flow. (Without a conditioner/coupling). I think the implementation can be quickly implemented in [build flow](https://github.com/lollcat/fab-jax/blob/main/fabjax/flow/build_flow.py) as distrax already provides a ScalarAffine Flow.  

But I don't know how to create the flow with trainable parameters for such a flow.

Simply returing a ScalarAffineFlow e.g
```
    def build_diagonal_affine_bijector(dim: int):
   
         shift = jnp.zeros(shape=(dim,))
         log_scale = jnp.zeros(shape=(dim,))
         return distrax.ScalarAffine(shift=shift, log_scale=log_scale)
```

doesn't work, as flow.init returns no parameter. (Which makes sense, as the bijector should be dependent on the state, and not be constant.

Thanks again for your support!

Best, Johannes

**Comment by lollcat** [comment]
Here is a hacky version that will work:

**Comment by lollcat** [comment]
The following should work (you just need to make sure that flax manages the parameters of the flow)
```
class ConstantParametersFn(nn.Module):
    name: str
    n_output_params: int

    @nn.compact
    def __call__(self):
        params = self.param(
            'parameters', nn.initializers.zeros_init(),
            (self.n_output_params,), jnp.float32
        )
        return params

def build_diagonal_affine_bijector(dim: int):
    shift = ConstantParametersFn("shift", dim)()
    log_scale = ConstantParametersFn("log_scale", dim)()
    return distrax.ScalarAffine(shift=shift, log_scale=log_scale)

```

**Comment by lollcat** [comment]
An affine (unconditional) transform applied to a Gaussian returns another Gaussian, so the resultant flow will just be a Gaussian with independant dimensions, and a trained mean and variance per dimension. Hence, I don't recommend doing this unless it is just for some simple testing.

**Comment by lollcat** [comment]
Let me know if this fixes your issue :)

**Comment by JohannesEsslinger** [comment]
Tanks again for the quick reply!

I really appreciate it.

Unfortunately, it doesn't work exactly as I had hoped.
First of all I adapted the make_bijector function:
```
    def make_bijector():
        # Note that bijector.inverse moves through this forwards, and bijector.forwards reverses the bijector order.
        if 'spline' == flow_type or 'real_nvp' == flow_type:
            bijectors = []
            bijector = build_split_coupling_bijector(
                dim=config.dim,
                identity_init=config.identity_init,
                conditioner_mlp_units=config.conditioner_mlp_units,
                transform_type=flow_type,
                restrict_scale_rnvp=config.restrict_scale_rnvp,
                spline_max=config.spline_max,
                spline_min=config.spline_min,
                spline_num_bins=config.spline_num_bins,
            )
            bijectors.append(bijector)

            if config.act_norm:
                bijectors.append(build_act_norm_layer(dim=config.dim, identity_init=config.identity_init))

            return ChainWithExtra(bijectors)

        elif 'diagonal_affine' == flow_type:
            bijector = build_diagonal_affine_bijector(
                dim=config.dim,
            )
            return bijector
        else:
            raise NotImplementedError("Unknown Flow Type")
```

So I can create a bijector to parameterize the flax modules in create_flow from flow.py:

```
def create_flow(recipe: FlowRecipe) -> Flow:
    """Create a `Flow` given the provided definition. Allows for extra info to be passed forward in the flow, and
    is faster to compile than the distrax chain."""

    bijector_block = recipe.make_bijector()
    ...
    forward_and_log_det_single = FlowForwardAndLogDet(bijector=bijector_block)
    inverse_and_log_det_single = FlowInverseAndLogDet(bijector=bijector_block)
```
But I encounter several errors, with your suggestion.

To fix it i changed the build_diagonal_affine_bijector to:
```
def build_diagonal_affine_bijector(dim: int):
    shift_fn = ConstantParametersFn(name="shift", n_output_params=dim)
    log_scale_fn = ConstantParametersFn(name="log_scale", n_output_params=dim)

    shift_param = shift_fn.init(jax.random.PRNGKey(0))
    log_scale_param = log_scale_fn.init(jax.random.PRNGKey(0))

    return distrax.ScalarAffine(shift=shift_fn.apply(shift_param), log_scale=log_scale_fn.apply(log_scale_param))
```

But then this is a dead end as I need the parameters in the init function in the FAB Architecture:
```    
def init(seed: chex.PRNGKey, sample: Sample) -> FlowParams:
        # Check shapes.
        chex.assert_tree_shape_suffix(sample, (recipe.dim,))

        key1, key2 = jax.random.split(seed)
        params_base = base_log_prob_fn.init(key1, sample)
        params_bijector_single = inverse_and_log_det_single.init(key2, sample)
```
Have I mixed something up or why does it not work?

Best regards,
Johannes!

**Comment by lollcat** [comment]
Here is a version that I tested with `gmm_v0` that works where we just replace the `make_conditioner` function for the split coupling flow (`fabjax/flow/build_coupling_bijector.py`) with an unconditional function. 

```
import flax.linen as nn
class ConstantParametersFn(nn.Module):
    name: str
    n_output_params: int

    @nn.compact
    def __call__(self):
        params = self.param(
            'parameters', nn.initializers.zeros_init(),
            (self.n_output_params,), jnp.float32
        )
        return params


def make_conditioner(name, n_output_params, mlp_units, identity_init):
    def conditioner(x: chex.Array) -> chex.Array:
        params = ConstantParametersFn(name=name, n_output_params=n_output_params)()
        if x.ndim != 1:
            assert x.ndim == 2
            params = jnp.repeat(params[None], x.shape[0], axis=0)
        return params
    return conditioner
```

This is super hacky as we aren't actually using the coupling mechanism - but it's easy to code as we can just make a simple adaption to the existing code. I assume the hacky-ness is okay as you are just using this for testing purposes?

**Comment by lollcat** [comment]
Your code has the following issues:
- you call `init` and `apply` inside `build_diagonal_affine_bijector` but these functions should only be called once when they are used inside `flow.py` [here](https://github.com/lollcat/fab-jax/blob/32d4d6521203e39384bdea674b19ea2d58455446/fabjax/flow/flow.py#L206). 
- You need to take care to only access the parameters during the forward pass of the flow, and not during it the flows construction (i.e. `build_diagonal_affine_bijector` constructs the flow bijector without doing a forward pass, so it **cannot** access the flax parameters. 

You can look at the split coupling flow code to see that it does not violate the above to bullet points. 
It was easier for me to just adjust the existing coupling flow architecture to satisfy these issues than implement the `ScalarAffine` bijector from scratch.

**Comment by lollcat** [comment]
Let me know if the code I sent fixes your issue!

**Comment by JohannesEsslinger** [comment]
Thanks again! 
Yes it was just for testing.
